name: Matrix
on: push
jobs:
  print:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print OS
        run: echo ${{ matrix.os }}
        shell: bash