name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    env:
      CONTAINS_FUNC: ${{ contains('Hello', 'el'') }}
    steps:
      - run: printenv | grep '_FUNC'
      - run: echo "${CONTAINS_FUNC}"
