name: Intermediate enviromnment variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{github.actor}}
    steps:
        - name: Print the actor
          run: echo "${{ACTOR}}"

    