name: Generate functions
on : [push]
jobs: 
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORK_FUNC: ${{ format('{0},{1}', 'fork', 'fork') }}
          JOIN_FUNC: ${{ join(github.event, ',') }}