name: Publish
on:
  workflow_dispatch:
    inputs:
      VERSION:
        type: string
        required: true
        description: バージョン（例:1.3.3)
env:
  IMAGE_NAME: gha-image
jobs:
  runs-on: ubuntu-latest
  permissions:
    packages: write
    contents: read
  steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/meta-action@v3
      id: meta
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{ version }},value=v${{ inputs.VERSION }}
          type=raw,value=latest
    - uses: docker/build-push-action@v2
      with:
        push: true
        context: docker/example
        tags: ${{ steps.meta.outputs.tags }}
        labels:
          ${{ steps.meta.outputs.labels }}